project_id = "irvpnyxtdzwpnhtdpweu"

[api]
enabled = true
port = 54321
max_rows = 1000

[functions.send-verification-email]
verify_jwt = true

[functions.send-reminder-emails]
verify_jwt = false

[functions.verify-geofence]
verify_jwt = true

[functions.send-whatsapp-verification]
verify_jwt = false

[functions.verify-whatsapp-token]
verify_jwt = false

[functions.verify-document]
verify_jwt = true

[functions.verify-id-photo]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = true

[functions.request-renewal-invitation]
verify_jwt = false

[functions.complete-employee-registration]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.update-admin-profile]
verify_jwt = false

[functions.reset-admin-password]
verify_jwt = false
