project_id = "irvpnyxtdzwpnhtdpweu"

[api]
enabled = true
port = 54321
max_rows = 1000

[functions.send-reminder-emails]
verify_jwt = false

[functions.verify-geofence]
verify_jwt = true

[functions.send-whatsapp-verification]
verify_jwt = false

[functions.verify-whatsapp-token]
verify_jwt = false

[functions.verify-document]
verify_jwt = true

[functions.verify-id-photo]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = true

[functions.request-renewal-invitation]
verify_jwt = false

[functions.complete-employee-registration]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = true

[functions.update-admin-profile]
verify_jwt = true

[functions.reset-admin-password]
verify_jwt = true

[functions.approve-pending-upload]
verify_jwt = true

[functions.extract-polygraph-report]
verify_jwt = true

[functions.get-invitation-method]
verify_jwt = false

[functions.verify-employee-login]
verify_jwt = false

[functions.link-employee-user]
verify_jwt = false

[functions.convert-docx-to-pdf]
verify_jwt = true

[functions.delete-admin-profile]
verify_jwt = true

[functions.resend-admin-credentials]

[functions.generate-pre-risk-profile]
verify_jwt = false
